name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Write .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Trigger Docker
        run: |
          sudo docker stop jewelsland-frontend-container || true
          sudo docker rm jewelsland-frontend-container || true
          sudo docker run -d --network=host --name jewelsland-frontend-container -p 3000:3000 --env-file .env jewelsland-frontend:latest
