name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Docker
        run: |
          docker stop jewelsland-frontend-container || true
          docker rm jewelsland-frontend-container || true
          docker run -d --name jewelsland-frontend-container -p 3000:3000 jewelsland-frontend:latest
